"""Initial Migration

Revision ID: 34712fc59bc5
Revises: 
Create Date: 2022-05-07 20:26:40.661178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34712fc59bc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=85), nullable=True),
    sa.Column('user_name', sa.String(length=85), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
