"""pitches X category

Revision ID: 378c007b1642
Revises: e41d7a7c3389
Create Date: 2022-05-10 12:54:37.158744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378c007b1642'
down_revision = 'e41d7a7c3389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'category_id')
    # ### end Alembic commands ###
