"""add colums to pitch

Revision ID: db432d33c01c
Revises: 753cb461ff11
Create Date: 2022-05-11 22:05:33.076988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db432d33c01c'
down_revision = '753cb461ff11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('upvote', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('downvote', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('comments', sa.String(length=255), nullable=True))
    op.alter_column('pitches', 'category_name',
               existing_type=sa.VARCHAR(length=220),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pitches', 'category_name',
               existing_type=sa.VARCHAR(length=220),
               nullable=True)
    op.drop_column('pitches', 'comments')
    op.drop_column('pitches', 'downvote')
    op.drop_column('pitches', 'upvote')
    # ### end Alembic commands ###
